// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(BackendContext))]
    partial class BackendContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Backend.Models.Ingatlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("Ar")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("HirdetesDatuma")
                        .HasColumnType("datetime2");

                    b.Property<int>("KategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("KepUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leiras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Tehermentes")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ingatlanok");
                });

            modelBuilder.Entity("Backend.Models.Kategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nev")
                        .IsUnique();

                    b.ToTable("kategoriak");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nev = "Ház"
                        },
                        new
                        {
                            Id = 2,
                            Nev = "Lakás"
                        },
                        new
                        {
                            Id = 3,
                            Nev = "Építési telek"
                        },
                        new
                        {
                            Id = 4,
                            Nev = "Garázs"
                        },
                        new
                        {
                            Id = 5,
                            Nev = "Mezőgazdasági terület"
                        },
                        new
                        {
                            Id = 6,
                            Nev = "Ipari ingatlan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
